# Generated by Django 3.1.7 on 2021-03-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeatSound',
            fields=[
                ('title', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('beat_image', models.ImageField(upload_to='beat_images')),
                ('beat_file', models.FileField(upload_to='beat_files')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('profile_pic', models.URLField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserSound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_audio', models.FileField(upload_to='user_audios')),
                ('user_score', models.FloatField()),
                ('beat_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beatapp.beatsound')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beatapp.userdata')),
            ],
        ),
    ]
